Linear cache: Avoid linear time iterations on all resources when applying delta updates. No longer build the versionMap when not using delta watches
envoyproxy/go-control-plane pull request #547
Opened 2022-03-17 18:57 UTC by valerian-roche

The linear cache is currently building the versionMap every time it is receiving any update
This is quite expensive currently in two cases:
* When not using delta watches, it is never used but constantly maintained. It is very expensive when using SetResources 
* When using delta watches and using delta updates (UpdateResource/DeleteResource/UpdateResources), it is iterating on the entire resource set instead of iterating on modified objects

Also adds a constant time accessor to the nb of entries in the cache as GetResources is no longer constant time

2022-03-23 19:46 UTC, alecholmez requested changes
Overall this looks good to me. Just a few nits in the comments but other than that seems like a solid performance increase. One of the things I actually need to get around to is porting over a change to the simple cache where we only hash on modified resources instead of the entire set. Nice addition for the linear cache

2022-03-23 19:46 UTC, alecholmez commented on pkg/cache/v3/linear.go
> +		// If we had no delta watch before, we need to build the version map for the first time.
```suggestion
		// If we had no previously open delta watches, we need to build the version map for the first time.
```

2022-03-23 19:46 UTC, alecholmez commented on pkg/cache/v3/linear.go
> +		// The map will not be removed when the last delta watch is removed to avoid rebuilding it constantly when only a few delta watches are applicable.
```suggestion
		// The version map will not be destroyed when the last delta watch is removed. 
		// This avoids constantly rebuilding when only a few delta watches are open.
```

2022-03-23 21:33 UTC, valerian-roche commented on pkg/cache/v3/linear.go
> +		// If we had no delta watch before, we need to build the version map for the first time.
Updated to match

2022-03-23 21:33 UTC, valerian-roche commented on pkg/cache/v3/linear.go
> +		// The map will not be removed when the last delta watch is removed to avoid rebuilding it constantly when only a few delta watches are applicable.
Updated to match

2022-03-23 21:35 UTC, valerian-roche commented
> Overall this looks good to me. Just a few nits in the comments but other than that seems like a solid performance increase. One of the things I actually need to get around to is porting over a change to the simple cache where we only hash on modified resources instead of the entire set. Nice addition for the linear cache

Not sure how the snapshot cache can be optimized on that. In most cases the user will rebuild the entire snapshot for the node. On the linear cache side this is really bad today to build the cache map with SetResources (in our production systems we reached ~1s spent just on it) so it can probably become quite bad for snapshot also
Are you planning on supporting delta snapshot updates on simple cache? That'd be very useful for us (e.g. if we want to use runtime flags in the same simple cache)

2022-03-24 19:56 UTC, alecholmez commented
@valerian-roche We would like to add support for incremental snapshot updates with delta. We have this open: https://github.com/envoyproxy/go-control-plane/issues/423

I haven't given much thought to it yet but I imagine that designing an API for per resource updates will significantly increase performance in the simple cache. We have a similar problem there where we're constantly building a big hash map regardless of what changed.

2022-03-24 19:56 UTC, alecholmez approved these changes

2022-03-24 19:56 UTC, merged

2022-03-25 13:39 UTC, valerian-roche commented
Definitely make sense to me to allow delta updates of snapshots, especially to no longer require to rebuild the entire snapshot to just update one resource 
Thanks for looking at improving that!